### ISSUE TITLE
Generates too long path on Windows

### ISSUE THREAD

**Issue by Trojaner** [angular/webdriver-js-extender#27] opened 2018-09-25 00:07 UTC
Visual Studio deployment fails because webdriver-js-extender generates paths which are too long on Windows (it fails to copy the output).

![](https://vgy.me/XGnzlW.png)

webdriver-js-extender@2.1.0
Node v8.9.1
Windows 10 x64 1803

Edit: #26 should fix it.

**Comment by AcidAndroid** [comment] 2018-12-13 21:50
I have the same problem. I delete the node_modules and the problem remains. Does anyone solve it?

**Comment by briankoksal** [comment] 2019-06-17 13:15
Same issue here. 

node_modules\webdriver-js-extender\built\built\built\built\built\built\built\built\built\built\built\built\built\built\built\built\spec\command_tests

**Comment by mkArtakMSFT** [comment] 2019-07-01 20:28
This is indeed a source of pain. Hopefully this will be fixed soon, though given the age of this issue seems like not 👎

**Comment by SwintDC** [comment] 2019-08-27 11:40
Does anyone have an idea what is causing this?

**Comment by kappa7194** [comment] 2019-09-25 08:55
We're having problem with this in our project on Windows.

We're unable to delete the node_modules directories from either Command Prompt or Git Bash because the path length exceeds the one supported by Windows.

This prevents us from automating build/clean-ups.

Issue #29 is a duplicate of this one.

**Comment by tudorsibiu90** [comment] 2019-11-25 14:56
I also experience this and I found no solution thus far. It's a deal breaker

**Comment by stoicad** [comment] 2020-01-08 14:58
Same here, do you have a solution for this??

**Comment by kyliau** [comment] 2020-05-27 21:35
This issue has been fixed in v2.2.0 release.

**Closed by kyliau** 2020-05-27 21:35 UTC
